### ISSUE TITLE
Looking for omada k8s manifest

### ISSUE THREAD

**Issue by x-real-ip** [frealmyr/homelab#5]
Hi, i found your repository from a [comment in Reddit ](https://www.reddit.com/r/selfhosted/comments/unyq9n/omadacontroller_kubernetes_k8s/?utm_source=share&utm_medium=web2x&context=3)about using TP-Link omada controller in k8s. I am searching for a good k8s manifest.yaml to deploy the Omada Controller i have tried the on from k8s-at-home but that one is'nt working for me. The device discovery doesnt work. Would you like to share your k8s deployment manifest so i cant try what you have made?

**Comment by frealmyr** [comment]
The helm chart is here: https://github.com/frealmyr/homelab/tree/provision/.archive/k8s/home/omada

And it uses this helm chart as a dependency: https://github.com/frealmyr/homelab/tree/provision/.archive/charts/app

I don't use k8s in my homelab atm, so i recommend that you take inspiration of the helm charts and make your own.

**Comment by frealmyr** [comment]
You'll also need cert-manager for automatically creating certificates, and then mount the secret containing said certificates into the pod.

**Comment by frealmyr** [comment]
Archived the Omada WebUI, reverse-proxy support is pretty hacky and the application itself was slow af.

I don't have that many devices at home, so i just use on-device configurations instead. (Which is accessible even if internet is down, or Omada Controller is broken.)

https://github.com/frealmyr/homelab/tree/main/.archive/k8s/omada
